### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by kakoni** [hishidama/embulk-parser-excel-poi#1]
Thanks for the great plugin!

I believe with the embulk 0.11 you can install this plugin using
1. `java -jar embulk-011.4.jar install "io.github.hishidama.embulk:embulk-parser-excel-poi:0.2.0"`
2. And then defining it as
```
  parser:
    type:
      source: maven
      group: io.github.hishidama.embulk
      name:  excel-poi
      version: 0.2.0
```
